---
name: Module-Finder
version: v0.1.2
author: []
abstract: find and query modules in @INC and/or elsewhere
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Module::Build: 0.26
  Test::More: 0
provides:
  Module::Finder:
    file: lib/Module/Finder.pm
    version: v0.1.2
  Module::Finder::Info:
    file: lib/Module/Finder.pm
generated_by: Module::Build version 0.280501
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
