---
name: Module-Finder
version: v0.1.5
author: []
abstract: find and query modules in @INC and/or elsewhere
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Module-Finder
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://scratchcomputing.com/svn/Module-Finder/trunk
requires:
  Class::Accessor::Classy: v0.1.3
  Module::Build: 0.26
  Test::More: 0
provides:
  Module::Finder:
    file: lib/Module/Finder.pm
    version: v0.1.5
  Module::Finder::Info:
    file: lib/Module/Finder.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
